### ISSUE TITLE
Formiz v2 - React 18

### ISSUE THREAD

**Issue by ivan-dalmet** [BearStudio/formiz#116]
## The v2 of Formiz is under heavy developments! 🎉
This v2 is focusing on performances, React 18 and internal code simplification for better contributions.
The [BearStudio](https://www.bearstudio.fr/) team is on the subject to release this new version as soon as possible. But we want to make sure that all the majors features of v1 will be supported and if not, to provide a migration guide. We hope to share an alpha with you before this summer 🤞

**Follow this issue if you want updates about future alpha, beta and rc 🙂**

**Comment by ivan-dalmet** [comment]
Hi @nickcanarelli, I know that we said "before the summer" 😅 But you know work, kids and holidays. 
We will try to give some update in September (may be expose a board with progress). We currently have most of features implemented with the new architecture based on zustand internally. We need to test more use cases, write the new documentation and write the migration guide for the breaking changes.
Sorry for the delay. Thanks for your interest 🙏

**Comment by kesm0** [comment]
Is v2 project still on ?

**Comment by ivan-dalmet** [comment]
> Is v2 project still on ?

Yes but not as fast as planned. Sorry for that 😕

**Comment by ivan-dalmet** [comment]
> Hi @ivan-dalmet No worries on the delay. Do you have a roadmap / feature list for v2?
> 
> It would help in planning

We have plans for the end of January to have a couple days to tackle a main performance issue that shouldn't be there but that happening 😕
I know it's very far away but agenda for the team are pretty hard to sync.

The main goal of this v2 is to simplify the internal code (remove rxjs to use zustand under the wood). This allows us to have a very easier core that can easily provide better hooks to do complexe forms. First we need to fix this performance issue and then we will release an alpha. 

We tried to give dates in the past and... well summer is in 7 months from now 😅

**Comment by ivan-dalmet** [comment]
https://v2.formiz-react.com/ beta is available 🤗
