### ISSUE TITLE
useForm is not working as expected.

### ISSUE THREAD

**Issue by aylonmuramatsu** [BearStudio/formiz#215]
## Describe the bug
When I use useForm in an Expo managed project, I receive an error related to the 'os' module. I can only use the project correctly when I add the 'os' library to my projects

## To Reproduce
1. Install formiz to expo managed app
2. import & use useForm

## Expected behavior

Being able to use formiz without installing an additional module
## Screenshots
![Screenshot 2024-01-23 at 10 35 08](https://github.com/BearStudio/formiz/assets/28609474/b8eaf5be-40b5-4ba4-9dc2-855346d3b4db)
![Screenshot 2024-01-23 at 09 29 30](https://github.com/BearStudio/formiz/assets/28609474/a897ade0-3fbc-483d-a2f0-35496ecf56e1)

## Smartphone (please complete the following information)

- Device: iPhone 15 Pro
- OS: IOS17.2

**Comment by yoannfleurydev** [comment]
Thanks a lot for your issue, it is indeed a bug coming from a Formiz peer dependency. I'm looking to replace that dependency.

**Comment by yoannfleurydev** [comment]
Hey @aylonmuramatsu thanks again for raising this issue. You can upgrade Formiz to `2.2.2` and remove the `os` dependency, and it should work. Let us know if there are others issues.
